-- Limpiar productos existentes
DELETE FROM productos;

-- Insertar productos de pastelería mexicana auténticos
INSERT INTO productos (id, nombre, descripcion, precio, imagen_url, categoria, created_at) VALUES
('1', 'Conchas Tradicionales', 'Pan dulce mexicano icónico con cobertura de azúcar en forma de concha, disponible en sabores de vainilla, chocolate y fresa. Horneado diariamente con ingredientes frescos.', 18, 'https://imgs.search.brave.com/ge1vv8dtyqmsC1C0GU8OlR_iCr_Fz0XzSl8i6CHZUtY/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvMTQx/NDQzMzI1NC9lcy9m/b3RvL2NvbmNoYXMt/cGFuLWR1bGNlLW1l/eGljYW5vLXBhbmFk/ZXIlQzMlQURhLXRy/YWRpY2lvbmFsLWRl/LW0lQzMlQTl4aWNv/LmpwZz9zPTYxMng2/MTImdz0wJms9MjAm/Yz05WjlYUFZfbExH/dTRycUxDNWdiUExf/bkt5MDJqNDVzLVQ0/X1RBLVlHU1NRPQ', 'Pan Dulce', NOW()),
('2', 'Pastel Tres Leches', 'Esponjoso pastel empapado en una mezcla de tres leches (evaporada, condensada y leche entera), cubierto con crema batida y decorado con frutas frescas.', 65, 'https://imgs.search.brave.com/pkIK7r0lpbKDXoPaI6CIPL1EEP0SIjO0l-xxGwxgY9w/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9kaXJl/Y3RvYWxndXN0by5j/b20vd3AtY29udGVu/dC91cGxvYWRzLzIw/MjUvMDIvY29tby1w/cmVwYXJhci1lbC1h/dXRlbnRpY28tcGFz/dGVsLXRyZXMtbGVj/aGVzLW1leGljYW5v/LTEwMjR4NTc2Lmpw/Zw', 'Pastel', NOW()),
('3', 'Churros Caseros', 'Palitos de masa frita crujientes espolvoreados con azúcar y canela, servidos tradicionalmente con salsa de chocolate para mojar.', 15, 'https://imgs.search.brave.com/lww0AOsJgxkG4ZalcDAsCJqbRtkGOAL4G1G-AuZrtoE/rs:fit:500:0:1:0/g:ce/aHR0cDovL2VuanVs/aWFuYS5jb20vdHVl/cmVzZWxjaGVmL3dw/LWNvbnRlbnQvdXBs/b2Fkcy8yMDE1LzAx/L2NodXJyb3MtY2Fz/ZXJvcy1jb24tYXol/QzMlQkFjYXIteS1j/YW5lbGEuanBn', 'Frito', NOW()),
('4', 'Pan de Muerto', 'Pan tradicional del Día de Muertos con aroma de flor de naranja, decorado con tiras que simulan huesos y recubierto de azúcar glass.', 35, 'https://imgs.search.brave.com/lIuept_4Bh-2gIsMRnQyhlVEjkcbPn-U0h4N2L4mmVI/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9jZG43/LnJlY2V0YXNkZWVz/Y2FuZGFsby5jb20v/d3AtY29udGVudC91/cGxvYWRzLzIwMjEv/MTEvUGFuLWRlLW11/ZXJ0by11bi1kdWxj/ZS10cmFkaWNpb25h/bC1tZXhpY2Fuby5q/cGc', 'Pan Dulce', NOW()),
('5', 'Buñuelos', 'Tortillas fritas delgadas y crujientes espolvoreadas con azúcar y canela, tradicionalmente disfrutadas durante la Navidad con jarabe de piloncillo.', 22, 'https://imgs.search.brave.com/KzIrWvDnb1pZbZVYsBMLqfwo7u7h1N-F-Wcl5BAKJN4/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9pbWcu/ZnJlZXBpay5jb20v/Zm90b3MtcHJlbWl1/bS9idW51ZWxvLW1l/eGljYW5vLWVzcG9s/dm9yZWFkby1henVj/YXItdGFtYmllbi1s/bGFtYWRvLXF1b3Ri/dW51ZWxvc3F1b3Rf/MzM4MzY3LTEyNzUu/anBn', 'Frito', NOW()),
('6', 'Marranitos (Puerquitos)', 'Galletas en forma de cerdo hechas con piloncillo (azúcar de caña sin refinar), calificadas como una de las mejores galletas del mundo por Taste Atlas.', 14, 'https://imgs.search.brave.com/WAGR2h1Bqqx_VzIuImJfF2QEBPSYXaQpPoTiVb7Gn6s/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9lZGl0/b3JpYWx0ZWxldmlz/YS5icmlnaHRzcG90/Y2RuLmNvbS9kaW1z/NC9kZWZhdWx0LzAy/MWQ5MjQvMjE0NzQ4/MzY0Ny9zdHJpcC90/cnVlL2Nyb3AvODk2/eDY3MisxNDcrMC9y/ZXNpemUvMTQ0MHgx/MDgwIS9xdWFsaXR5/LzkwLz91cmw9aHR0/cHM6Ly9rMi1wcm9k/LWVkaXRvcmlhbC10/ZWxldmlzYS5zMy51/cy1lYXN0LTEuYW1h/em9uYXdzLmNvbS9i/cmlnaHRzcG90L2Y0/LzBlLzNlOTVkMTQz/NGQzZWIwY2VjNzlj/OGY0ZjVjNjgvcHVl/cnF1aXRvcy1kZS1w/aWxvbmNpbGxvLXJl/Y2V0YS1mYWNpbC15/LXJhcGlkYS5qcGVn', 'Galleta', NOW()),
('7', 'Empanadas Dulces', 'Pasteles dulces rellenos de guayaba, calabaza o camote, fritos u horneados hasta dorar y quedar crujientes.', 28, 'https://imgs.search.brave.com/R9tkaNl6-ehwKljUGh8RDeXvzQuaszyaLmP9NptsFD4/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9kaW5v/cmFuay5jb20vaW1n/L2Rpbm9icmFpbi8x/OTk0NTEvaW1hZ2Vu/MGRkNDdiZjYxOWM5/MTEzZGM3MDZhZDZm/Yjg4YjNmOTMuanBn', 'Pastel', NOW()),
('8', 'Pan de Elote', 'Pan dulce húmedo de maíz hecho con granos de maíz frescos, que encarna la herencia indígena del maíz de México. Perfecto con café.', 38, 'https://imgs.search.brave.com/pye1oRc-BVT-0-x5IF7n7jS4YlozxstJ0y8Q5eqSxM4/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9tdXli/dWVub2Jsb2cuY29t/L3dwLWNvbnRlbnQv/dXBsb2Fkcy8yMDIz/LzAzL1Bhbi1kZS1F/bG90ZS1NZXhpY2Fu/by1NZXhpY2FuLVN3/ZWV0LUNvcm4tQ2Fr/ZS5qcGVn', 'Pan Dulce', NOW()),
('9', 'Cocadas', 'Dulces a base de coco horneados en forma de nido, hechos con coco, azúcar y huevos. Un favorito de la época colonial.', 25, 'https://imgs.search.brave.com/dIU10l7rwf69YrcrM9Utger-48kXowW4MIqC6Ke5tNs/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9lc3F1/aW5hbXguZXMvd3At/Y29udGVudC91cGxv/YWRzLzIwMjQvMDkv/eDMwaXV5Nzk2dmUu/anBn', 'Dulce', NOW()),
('10', 'Chocoflan', 'Pastel "imposible" que combina capas de pastel de chocolate y flan que mágicamente cambian de posición durante el horneado.', 78, 'https://imgs.search.brave.com/jiywmDSiGvOABYMwlLyhhTRygwRFxfvbFPudsvaZIxs/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93d3cu/aG9sYWphbGFwZW5v/LmNvbS93cC1jb250/ZW50L3VwbG9hZHMv/MjAyMy8wNS9jaG9j/b2ZsYW4ta2F0ZS1y/YW1vcy0xMDI0eDY4/My5qcGc', 'Pastel', NOW()),
('11', 'Flan Mexicano', 'Postre cremoso de natillas con rica salsa de caramelo, una importación española que se convirtió en un básico mexicano.', 42, 'https://imgs.search.brave.com/hcc8YW1Q5dqCdK5pvBps3jDDdCd0DonDDUo7YGQ54ys/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93d3cu/Y29jaW5hcmVjZXRh/c2ZhY2lsZXMuY29t/L3dwLWNvbnRlbnQv/dXBsb2Fkcy8yMDI0/LzA3L2ZsYW4tbmFw/b2xpdGFuby1tZXhp/Y2Fuby5qcGc', 'Postre', NOW()),
('12', 'Arroz con Leche', 'Pudín de arroz tradicional sazonado con canela y vainilla, que evoca tradiciones familiares y comodidad.', 32, 'https://imgs.search.brave.com/uKwKyYVfudyoEFtcxZMTbH-FS7PnDjghsuoI4ObE-TQ/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93d3cu/bWFyaWNydXphdmFs/b3MuY29tL3dwLWNv/bnRlbnQvdXBsb2Fk/cy8yMDIwLzA5L2Fy/cm96LWNvbi1sZWNo/ZS1tZXhpY2Fuby5q/cGc', 'Postre', NOW()),
('13', 'Dulce de Zapote Negro con Naranja', 'Postre único de Veracruz hecho con pulpa de zapote negro, jugo de naranja, azúcar y un toque de ron. Oscuro, cremoso y exótico.', 52, 'https://imgs.search.brave.com/0jwFhCHhTIREojV41kr_mh766zmCKAMrlSMMT5ZbXb0/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9pMC53/cC5jb20vd3d3LmN1/Ym9pbmZvcm1hdGl2/by50b3Avd3AtY29u/dGVudC91cGxvYWRz/LzIwMjAvMDQvRHVs/Y2UtZGUtWmFwb3Rl/LU5lZ3JvLWNvbi1O/YXJhbmphLmpwZz9y/ZXNpemU9NDcwLDMz/NyZzc2w9MQ', 'Postre', NOW()),
('14', 'Glorias de Veracruz', 'Postre icónico de Veracruz de hielo raspado con plátano machacado, jarabes, leche condensada, leche evaporada, vainilla y canela.', 35, 'https://imgs.search.brave.com/f6Hrxb8iZGgCHFqC4GOPXzW9-W-WJXuvoum790jbvLw/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93d3cu/Z29iLm14L2Ntcy91/cGxvYWRzL2FydGlj/bGUvbWFpbl9pbWFn/ZS85NjQwNC9HTE9S/SUFTU0lUSU8uanBn', 'Raspado', NOW()),
('15', 'Pan de Natas Veracruzano', 'Pan dulce hecho con nata (piel de leche), harina, azúcar y canela. Una especialidad veracruzana asequible, cremosa y crujiente.', 26, 'https://imgs.search.brave.com/pcfUVELORi2fPGytosIZnkTgoWtclAvI_eHNaJ9tuIk/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9lZGl0/b3JpYWx0ZWxldmlz/YS5icmlnaHRzcG90/Y2RuLmNvbS9kaW1z/NC9kZWZhdWx0L2Y3/OGFlMTEvMjE0NzQ4/MzY0Ny9zdHJpcC90/cnVlL2Nyb3AvNTYw/eDU2MCsyMjArMC9y/ZXNpemUvMTAwMHgx/MDAwIS9xdWFsaXR5/LzkwLz91cmw9aHR0/cHM6Ly9rMi1wcm9k/LWVkaXRvcmlhbC10/ZWxldmlzYS5zMy51/cy1lYXN0LTEuYW1h/em9uYXdzLmNvbS9i/cmlnaHRzcG90L3dw/LWNvbnRlbnQvdXBs/b2Fkcy8yMDE3LzA5/L3Bhbi1kZS1uYXRh/LmpwZw', 'Pan Dulce', NOW()),
('16', 'Torta de Elote Veracruzana', 'Pastel tradicional de maíz de Veracruz hecho con granos de maíz frescos, crema, azúcar y huevos, con un color amarillo distintivo.', 58, 'https://imgs.search.brave.com/drT665fSJFWkx6dytrVwFEItqi4_CkRhJNde2_NdCR0/rs:fit:500:0:1:0/g:ce/aHR0cDovL2xhY29j/aW5hZGV2ZXJvLmNv/bS93cC1jb250ZW50/L3VwbG9hZHMvMjAy/MC8wNi9Ub3J0YS1k/ZS1lbG90ZS12ZXJh/Y3J1emFuYS0xLTY4/MHgxMDI0LmpwZw', 'Pastel', NOW()),
('17', 'Alfajores de Veracruz', 'Pastelería de origen español adaptada en Veracruz con maíz blanco local, piloncillo y canela. Textura crujiente con relleno de miel.', 24, 'https://imgs.search.brave.com/AqEZQMUDxOeXez9CdfWGR_MHPjADXwuJA4Qv2_6Z5io/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9sYWd1/YWRhLmNvbS93cC1j/b250ZW50L3VwbG9h/ZHMvMjAyNC8wMS9h/bGZham9yZXMtdmVy/YWNydXphbm9zLmpw/Zw', 'Galleta', NOW()),
('18', 'Dulce de Leche de Tlacotalpan', 'Dulce icónico de Veracruz de Tlacotalpan, hecho con leche y azúcar cocinados lentamente hasta espesar, con variantes de coco o almendra.', 48, 'https://imgs.search.brave.com/6jVOdCE6mr0MCKIVghGbGR5cz-hPwlqjXV4udS5no1c/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9odHRw/Mi5tbHN0YXRpYy5j/b20vRF9RX05QXzJY/XzcxMTQ4NC1NTE00/ODc2MjA5MTI0M18w/MTIwMjItVi1kdWxj/ZS1tZXhpY2Fuby10/cmFkaWNpb25hbC1k/ZS1sZWNoZS53ZWJw', 'Dulce', NOW());

-- Verificar que se insertaron correctamente
SELECT COUNT(*) as total_productos FROM productos; 